### ISSUE TITLE
Getting 403 error on vps

### ISSUE THREAD

**Issue by ashwinstr** [johnwmillr/LyricsGenius#220]
Showing 403 error when trying to search for lyrics while test running on github workflow

**Expected behavior**
was expecting lyrics from the api

**To Reproduce**
the code is as follows:

```import GENIUS
import lyricsgenius
if GENIUS is not None:
    genius = lyricsgenius.Genius(GENIUS)
song = "hawayein"
artist = "arijit singh"
songs = genius.search_songs(f"{artist} {song}")
song_id =  songs["hits"][0]["result"]["id"]
await message.reply(genius.lyrics(song_id))```

the error is

```Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/lyricsgenius/api/base.py", line 80, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://genius.com/Arijit-singh-hawayein-lyrics```

**Version info**
 - Version: 3.0.1
 - OS: windows

**Additional context**
same error comes after directly trying to get the lyrics with:

```import GENIUS
import lyricsgenius
if GENIUS is not None:
    genius = lyricsgenius.Genius(GENIUS)
song = "hawayein"
artist = "arijit singh"
songs = genius.search_songs(f"{artist} {song}")
lyrics = songs.lyrics```

**Comment by TabulateJarl8** [comment]
I get the same error on an Azure Virtual Machine running Ubuntu 20.04. I also get the error when I write the scraping code myself, but with an added user agent header. Can't seem to find away around this one

**Comment by ju** [comment]
having this same isuse on Ubuntu 20.04

**Comment by TabulateJarl8** [comment]
I was looking qt the issues yesterday and saw that the same thing was reported in #190. There doesn't seem to be a solution unfortunately, so I switched to using some other API which actually let me retrieve lyrics instead of having to scrape a website, which was [https://lyrics.ovh/](https://lyrics.ovh/)

**Comment by Mohammad9760** [comment]
I am getting the same error now ... frustrating

**Comment by AkiArasaki** [comment]
I'm getting the same error on oracle VPS ubuntu 22.04

**Comment by nsde** [comment]
Same here :(

**Comment by sofijakrivokapic** [comment]
Hey! I am actually getting 403 error when I try to run .search_artist() . The token is correct, and the code works on .search_songs(), but not when I try to search artist. Is anyone having a similar problem or has already found the solution?

**Comment by sofijakrivokapic** [comment]
Yes, indeed, it only works locally. Thank you.
