### ISSUE TITLE
Circular import with song.py and album.py

### ISSUE THREAD

**Issue by VslVictor7** [johnwmillr/LyricsGenius#279]
**Bug:**
Seems like song.py and album.py are trying to import modules from each other, which is possibly why im getting this error.

"Traceback (most recent call last):
  File "D:\Minecraft Servers\Status-Manager-Bot\bot\core\main.py", line 10, in <module>
    from commands import setup_commands
  File "D:\Minecraft Servers\Status-Manager-Bot\bot\core\commands.py", line 8, in <module>
    from musica import lyrics_finder
  File "D:\Minecraft Servers\Status-Manager-Bot\bot\core\musica\lyrics_finder.py", line 1, in <module>
    from lyricsgenius import Genius
  File "D:\Minecraft Servers\Status-Manager-Bot\venv\Lib\site-packages\lyricsgenius\__init__.py", line 8, in <module>
    from lyricsgenius.genius import Genius
  File "D:\Minecraft Servers\Status-Manager-Bot\venv\Lib\site-packages\lyricsgenius\genius.py", line 16, in <module>
    from .types import Album, Artist, Song, Track
  File "D:\Minecraft Servers\Status-Manager-Bot\venv\Lib\site-packages\lyricsgenius\types\__init__.py", line 2, in <module>
    from .album import Album, Track
  File "D:\Minecraft Servers\Status-Manager-Bot\venv\Lib\site-packages\lyricsgenius\types\album.py", line 4, in <module>
    from .song import Song
  File "D:\Minecraft Servers\Status-Manager-Bot\venv\Lib\site-packages\lyricsgenius\types\song.py", line 8, in <module>
    from .album import Album
ImportError: cannot import name 'Album' from partially initialized module 'lyricsgenius.types.album' (most likely due to a circular import) (D:\Minecraft Servers\Status-Manager-Bot\venv\Lib\site-packages\lyricsgenius\types\album.py)"

**Version info:**
 - Latest master branch, commit: d4015f3
 - OS: Windows 11
 - Python 3.11.9

**Comment by allerter** [comment]
Thank you for this. I added a fix in #280, and we need to wait for the owner to merge it.
Until then you can install from the previous commit:

`pip install pip install git+https://github.com/johnwmillr/LyricsGenius.git@4671f043cea5535f7dc4affbd55803ae5a1ec6a4`

**Comment by VslVictor7** [comment]
Tysm for looking into this, commit ee6c7fb seems stable in my testing.
