### ISSUE TITLE
Adding Album to Song class causes a circular import error

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/LyricsGenius#285]
**Describe the bug**
There is currently a circular import between `song.py:Song` and `album.py:Album`. PR #276 added `Album` as an attribute on `Song`, introducing the circular import. The circular import appears to break the `search_album` function, if not the entire package.

**To Reproduce**
Attempting to run the unit tests demonstrates the error.

Include the error message associated with the bug:

```
Traceback (most recent call last):
  File ".pyenv/versions/3.8.12/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File ".pyenv/versions/3.8.12/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "LyricsGenius/tests/test_utils.py", line 9, in <module>
    from tests import genius
  File "LyricsGenius/tests/__init__.py", line 3, in <module>
    from lyricsgenius import Genius
  File "LyricsGenius/lyricsgenius/__init__.py", line 8, in <module>
    from lyricsgenius.genius import Genius
  File "LyricsGenius/lyricsgenius/genius.py", line 16, in <module>
    from .types import Album, Artist, Song, Track
  File "LyricsGenius/lyricsgenius/types/__init__.py", line 2, in <module>
    from .album import Album, Track
  File "LyricsGenius/lyricsgenius/types/album.py", line 4, in <module>
    from .song import Song
  File "LyricsGenius/lyricsgenius/types/song.py", line 9, in <module>
    from .album import Album
ImportError: cannot import name 'Album' from partially initialized module 'lyricsgenius.types.album' (most likely due to a circular import) (LyricsGenius/lyricsgenius/types/album.py)
```

**Version info**
 - 3.1.1

**Additional context**
[Reported](https://github.com/johnwmillr/LyricsGenius/issues/282#issuecomment-2540610634) on #282.

**Comment by johnwmillr** [comment]
Duplicate of #279.
